In [1]:
import numpy as np



In [10]:
# 1D array
a = np.array([2, 5, 6, 9])  

# 2D array
b = np.array([
    [3.5, 4.0, 6.5], 
    [0.4, 0.9, 4.7],
])

# 3D array
c = np.array([
    [
        [7, 1],
        [9, 4],
        [2, 3],
    ],
    [
        [4, 5],
        [0, 6],
        [8, 0],
    ],
    [
        [1, 3],
        [3, 9],
        [6, 9],
    ],
    [
        [5, 8],
        [8, 8],
        [4, 7],
    ],
])

In [20]:
e = np.loadtxt('numbers.txt',delimiter=',')

In [21]:
print(e)

[[7. 1.]
 [9. 4.]
 [2. 3.]
 [4. 5.]
 [0. 6.]
 [8. 0.]
 [1. 3.]
 [3. 9.]
 [6. 9.]
 [5. 8.]
 [8. 8.]
 [4. 7.]]


In [12]:
a.sum()

22

In [14]:
b.sum()

20.0

In [16]:
b.sum(axis=0)

array([ 3.9,  4.9, 11.2])

In [22]:
b.sum(axis=1)

array([14.,  6.])

In [24]:
e.ndim

2

In [25]:
c.ndim

3

In [27]:
e.reshape(4,3,2)

array([[[7., 1.],
        [9., 4.],
        [2., 3.]],

       [[4., 5.],
        [0., 6.],
        [8., 0.]],

       [[1., 3.],
        [3., 9.],
        [6., 9.]],

       [[5., 8.],
        [8., 8.],
        [4., 7.]]])