# Question 1

Follow the Github tutorial and do the following:

1. create a repo named `misy225-github-lab` and have a least two commits (you can add files or change files). Change the repo to public and add the repo URL below:

Your repo URL: [https://github.com/Lahmm/misy225-github-lab](https://github.com/Lahmm/misy225-github-lab)


2. issue a pull request to https://github.com/hjwang/misy225-f22 repo by adding a new text file named `your_full_name.txt` with any content you want. Add your pull request url below:

Your Pull Request URL: [https://github.com/hjwang/misy225-f22/pull/59](https://github.com/hjwang/misy225-f22/pull/59)

# Question 2

Read the numbers in the text file used in the lecture and generate the following numpy array:

```
[[[7. 1. 9. 4.]
  [2. 3. 4. 5.]]

 [[0. 6. 8. 0.]
  [1. 3. 3. 9.]]

 [[6. 9. 5. 8.]
  [8. 8. 4. 7.]]]
  ```

  then generate the following array (hint: 21 = 7 + 1 + 9 + 4):

  ```
  [[21. 14.]
 [14. 16.]
 [28. 27.]]

 ```


In [1]:
import numpy as np

matrix = np.loadtxt('numbers.txt', delimiter=',')

e = matrix.reshape(3,2,4)





In [2]:
e


array([[[7., 1., 9., 4.],
        [2., 3., 4., 5.]],

       [[0., 6., 8., 0.],
        [1., 3., 3., 9.]],

       [[6., 9., 5., 8.],
        [8., 8., 4., 7.]]])

In [3]:
e.sum(axis=2)

array([[21., 14.],
       [14., 16.],
       [28., 27.]])